config/routes.rb
Rails.application.routes.draw do
 
  root 'application#home'
  

  get 'signin', to: 'sessions#new'
  post 'signin', to: 'sessions#create'

  get '/auth/:provider/callback', to: 'sessions#omniauth'

  delete 'signout', to: 'sessions#destroy'

  get 'signup', to: 'students#new'
  post 'signup', to: 'students#create'


  resources :scribbles

  resources :classrooms do 
    resources :notes, only: [:new, :create, :index]
  end

  resources :students do 
    resources :notes 
  end


#  get "/search", to: "students#search"
    
 get '/search' => 'students#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/classroom.rb
class Classroom < ApplicationRecord
  belongs_to :student



  has_many :scribbles 
  has_many :notes, through: :scribbles

  validates :subject, presence: true 
  
end

app/models/note.rb
class Note < ApplicationRecord

    belongs_to :student 
    has_many :scribbles
    has_many :classrooms, through: :scribbles


    # accepts_nested_attributes_for :classrooms

    validates :title,  presence: true
    validates :content, presence: true
    validates :student_id, presence: true




    scope :ordered_by, -> { order('created_at DESC') }

    scope :shared, -> { joins(:scribbles).where('scribbles.sharable =?', true) }
end

app/models/scribble.rb
class Scribble < ApplicationRecord
  belongs_to :note
  belongs_to :classroom



  # scope :sharable_note, ->{where(sharable: true)}

end

app/models/student.rb
class Student < ApplicationRecord
    has_secure_password

    has_many :classrooms
    has_many :notes 


    validates :username, presence: true 

    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method  :current_student, :logged_in?


    def home 
    end

    

    def logged_in? 
        !!session[:student_id]
    end

    def current_student 
        @current_student ||= Student.find(session[:student_id]) if session[:student_id]
    end

    def authorized?
        redirect_to '/' if !logged_in?
    end




end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
   
   before_action :authorized?
  
    def new
        @classroom = Classroom.new
    end

    def create 
        binding
        @classroom = Classroom.new(classroom_params)
       
        if @classroom.save
          
            current_student.classrooms << @classroom
            redirect_to classrooms_path
        else
     
            @classroom.errors.full_messages
            render :new
        end
    end



    def index 
        @classrooms = current_student.classrooms
        @allclassrooms = Classroom.all 
    end

    
    def show
        @classroom = Classroom.find_by(id: params[:id])
       
    end

   private 

   def classroom_params 
    params.require(:classroom).permit(:subject, :student_id)
   end
    
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
    before_action :authorized?
   
    def index 
          if params[:classroom_id]
            @student = current_student
            @classroom = find_classroom
            @notes = @classroom.notes.ordered_by.shared
          else
            @notes = Note.all
          end
    end


    def new
        if  params[:student_id]
            @student = current_student
            @note = @student.notes.build
            # binding.pry
        else
            render :new
        end
    end


    def create 
        if  params[:student_id]
            @student = current_student
            @note = @student.notes.build(student_notes_params)
                if @note.save
                    binding.pry 
                    redirect_to student_path(current_student)
                else
                    render :new
                end
        else
            binding.pry
            redirect_to student_path(current_student)
        end
    end


    def show 
        @note = Note.find_by(id: params[:id])
    end



    def edit 
        if params[:student_id]
            @student = current_student
            @note = Note.find_by(id: params[:id])
        else
            redirect_to student_path(current_student)
        end
    end

    def update 
        if params[:student_id]
            @student = current_student
            @note = Note.find_by(id: params[:id])
                if @note.update(student_notes_params)
                 redirect_to student_note_path(current_student, @note)
                end
        else
            render :edit
        end
    end

    def destroy 
        @note = Note.find_by(id: params[:id])
        @note.delete
        redirect_to student_path(current_student)
    end



    private 


    def notes_params 
        params.require(:note).permit(:title, :content)
    end

    def student_notes_params 
        params.require(:note).permit(:title, :content, :student_id)
    end

    def find_classroom
        @classroom = Classroom.find_by_id(params[:classroom_id])
    end
   

end

app/controllers/scribbles_controller.rb
class ScribblesController < ApplicationController
    
    before_action :authorized?
    

    def new 
        @scribble = Scribble.new
    end

     
    def create
        @student = current_student
        @scribble = Scribble.new(scribble_params)
        if @scribble.save 
            current_student.classrooms << @scribble.classroom
            redirect_to scribble_path(@scribble)
        else
            render :new
        end
    end

    def show 
        @scribble = Scribble.find_by(id: params[:id])
        redirect_to student_path(current_student)
    end


   

    private 

        def scribble_params 
            params.require(:scribble).permit(:note_id, :classroom_id, :sharable)
        end

    

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController 
    #this is to track whos logged in
    def new 
    end


    def omniauth
        @student = Student.find_or_create_by(username: auth["info"]["first_name"]) do |s| 
            s.username = auth["info"]["first_name"]
            s.password = SecureRandom.hex(7)
        end
        if @student.save 
            session[:student_id] = @student.id
            redirect_to student_path(@student)
        else
            redirect_to '/'
        end

    end

    
    def create 
        @student = Student.find_by(username: params[:username])
        if @student && @student.authenticate(params[:password])
            session[:student_id] = @student.id
            redirect_to student_path(@student)
        else
            flash[:message] = "Hold UP, Lets Try That Again "
            binding.pry
            redirect_to signin_path
           
        end 
    end


    
    def destroy 
        session.clear 
        redirect_to signin_path
    end

    private 

    def auth
        request.env['omniauth.auth']
    end


end

app/controllers/students_controller.rb
class StudentsController < ApplicationController


    def new 
        @student = Student.new 
    end


    def create 
        @student = Student.new(student_params)
        if @student.save
            session[:student_id] = @student.id
            redirect_to student_path(@student)
        else
            render 'new'
        end
    end

    def show 
        authorized?
        @student = Student.find_by_id(params[:id])
        redirect_to '/' if !@student
    end

    def search 
        # binding.pry 
        if params[:search].blank?
            redirect_to student_path(current_student)
        else
            @parameter = params[:search].downcase  
            @results = Note.all.where("lower(title) LIKE :search", search: @parameter)  
        end
    end


    private 

    def student_params
        params.require(:student).permit(:username, :password, :uid, :provider)
    end

   

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/scribbles_helper.rb
module ScribblesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/application/home.html.erb
<h1> Welcome To Notes APP</h1>

app/views/classrooms/index.html.erb
<h1>Your Classrooms</h1>


<ul class="list-group list-group-flush">
    <% @classrooms.each do |c|  %>
        <li class="list-group-item"><%= link_to c.subject, classroom_path(c)%></li>
    <% end %>
</ul>
<br>
<br>
<br>
<br>

Here are all the Classrooms:

<ul class="list-group list-group-flush">
    <% @allclassrooms.each do |c|  %>
        <li class="list-group-item"><%= link_to c.subject, classroom_path(c) %></li>
    <% end %>
</ul>

<br>
<br>
<br>
<br>



<%= link_to "Add New Class", new_classroom_path, class: "btn btn-primary btn-lg"%>

app/views/classrooms/new.html.erb
<h1>Create a new Class: </h1>

<%= form_with model: @classroom do |f| %>

    <%= f.label :subject%>
    <%= f.text_area  :subject %>

 

    <%= f.hidden_field :student_id, value: "#{current_student.id}"%>

    <%= f.submit%>
<% end %>

app/views/classrooms/show.html.erb
<div class="jumbotron">
  <h1 class="display-4">Welcome to <%= @classroom.subject%> Class </h1>
  <p class="lead"></p>
  <hr class="my-4">
  <%# <p>It uses utility classes for typography and spacing to space content out within the larger container.</p> %>
  <%= link_to "All Notes", "/classrooms/#{@classroom.id}/notes", class: "btn btn-primary btn-lg"%> || 
  <%# <%= link_to "New Note", "/classrooms/#{@classroom.id}/notes/new", class: "btn btn-primary btn-lg"%> 
     <a class="btn btn-primary btn-lg" <%= link_to 'Back', classrooms_path %></a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Note30</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar'%>
    <%= yield %>
  </style=>
</html>

app/views/notes/edit.html.erb
<h1>Edit this Note </h1>


<div class="jumbotron">

  <h1 class="display-3">Let's Edit This Note</h1>
   <%= form_for ([@student, @note]) do |f|%> 
        <p class="lead">
            <%= f.label :title %>
            <%= f.text_field :title, placeholder: "Enter a Title"%>
        </p>


        <hr class="my-4">
        <p>
          <%= f.label :content%>
          <%= f.text_area :content, size: "70x5", placeholder: "Type your notes here."%>
        </p>

       
  

        <%= f.submit "Submit", class: "btn btn-primary btn-lg" %>
  <% end %>
  
</div>

app/views/notes/index.html.erb
<h1> </h1>



I want to be able to input note title and get back that note... 





<div class="jumbotron jumbotron-fluid">
   <div class="container">
      <h1 class="display-4">All Notes for <%= @classroom.subject%> Class </h1>
      <p class="lead"> </p>
      <hr class="my-4">
      <p>
            <% @notes.uniq.each do |n| %>
                  <li> <%= link_to n.title, student_note_path(current_student, n) %> - Owner: <%= n.student.username%></li>
               <% end %>
         </p>
         <br>
       <a class="btn btn-primary btn-md" <%= link_to 'Back', :back %></a> 
   </div>
</div>

app/views/notes/new.html.erb
<% if @note.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

    <ul>
      <% @note.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>




<div class="jumbotron">
  



    <h1 class="display-3">Let's Add A New Note</h1>
        <%= form_for ([@student, @note]) do |f|%> 
            <p class="lead">
                <%= f.label :title %>
                <%= f.text_field :title, placeholder: "Enter a Title"%>
            </p>


            <hr class="my-4">
            <p>
              <%= f.label :content%>
              <%= f.text_area :content, size: "70x5", placeholder: "Type your notes here."%>
            </p>

          

            <%= f.submit "Submit", class: "btn btn-primary btn-lg" %>
      <% end %>
    
</div>

app/views/notes/show.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4"><%= @note.title %></h1>
    <p class="lead"><%= @note.content%></p>
  </div>
</div>



<% if @note.student_id == current_student.id %>
   <%= link_to "Edit", edit_student_note_path(current_student, @note),  class: "btn btn-info"%> | 
  <%= link_to "Delete Note", student_note_path(current_student, @note), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %> |   
   
    <a class="btn btn-primary btn-md" <%= link_to 'Back', :back %></a>
<% else %>
    <%# <%= link_to "All Notes", notes_path %> 

    <a class="btn btn-primary btn-md" <%= link_to 'Back', :back %></a>
<% end %>

app/views/scribbles/new.html.erb
<h1>THis is Scribble Form</h1>



<%= form_with model: [@student, @scribble] do |f| %>
    <%= f.collection_select :classroom_id, Classroom.all, :id, :subject %>
   <%= f.collection_select :note_id,  current_student.notes, :id, :title %>
   <%= f.label :sharable%>
   <%= f.check_box :sharable, {}, true, false %>
    
    <%= f.submit%>
    
<% end %>

app/views/scribbles/show.html.erb
<h1>Here are Notes for <%= @sribble.classroom.subject %> </h1> 

<liL>
<%= link_to @scribble.note.title, student_note_path(current_student, @scribble.note.id) %>
</li>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
        <% if session[:student_id].nil? == false%>
            <a class="navbar-brand" <%= link_to "NoteApp", student_path(current_student)%></a>
        <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="nav nav-tabs">
                <% if session[:student_id].nil? == false%>
                    <li class="nav-item">
                        <%= link_to "New Note", new_student_note_path(current_student), class: "nav-link"%>
                    </li>
                    <li class="nav-item">
                        <%= link_to "Classrooms", classrooms_path, class: "nav-link"%>
                    </li>
                   <li class="nav-item">
                        <%= link_to "link Note and Classroom", new_scribble_path, class:" nav-link" %> 
                    </li> 
                    <li class="nav-item">
                        <%= link_to "Sign Out",signout_path, method: :delete, class: "nav-link"%>
                    </li>
            <% else %>
                    <li class="nav-item">
                        <%= link_to "Sign In",signin_path, class: "nav-link"%>
                    </li>
                    <li class="nav-item">
                        <%= link_to "Sign Up", new_student_path, class: "nav-link"%>
                    </li>
    
            <% end %>
        </ul>
    </div>
   
  </div>
</nav>























  

       
  

app/views/students/new.html.erb
<h1> New Student </h1>


<% if @student.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

    <ul>
      <% @student.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>




<%= form_with model: @student do |f| %>

    <%= f.label :username %>
    <%= f.text_field :username %>

    <br><br>

    <br><br>

    <%= f.label :password %>
    <%= f.password_field :password %>

    <br><br>

    <%= f.submit "Sign UP" %>
<% end %>




<%= button_to "Log in with Google", '/auth/google_oauth2' %>

app/views/students/search.html.erb
<h3>Search Result</h3>  




    <% @results.each do |result| %>  
        <%= result.title %><br>  
        <%= result.content %>
    <% end %>

app/views/students/show.html.erb
<%= form_tag ("/search"), method: :get do%>
     <%= text_field_tag :search, params[:search], placeholder: "Search" %> 
    <%=submit_tag "Search", :class => 'btn btn-info glyphicon glyphicon-search' %>
<% end %>





<div class="jumbotron jumbotron-fluid">
  <div class="container">
   <h1 class="display-2">Welcome <%= @student.username %></h1>
    <p class="lead"> Here are all  your notes: </p>

      <% current_student.notes.each do |n| %>
        <li>  <%= link_to n.title, student_note_path(current_student, n)%> </li>
      <% end %>
        
    
  </div>

<br><br>

  <div class="container">
       <p class="lead"> Here are all  your classes: </p>
        
      <% current_student.classrooms.each do |c| %>
        <li>  <%= link_to c.subject, classroom_path(c)%> </li>
      <% end %>




  </div>
</div>